# Generated by Django 6.0.6 on 2026-06-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='destacado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
